//Eleanor is on the way.
var config = {
    // 
    lines: [
        "亲爱的小锅锅",
        "花开一季，落叶为证",
        "逝去的岁月，如何能托于烟尘",
        "你的浅笑，是我永生眷恋",
        "眷念的真情，是否能明白一二",
        "亲爱的宝贝，你是我的唯一",
        "爱你永远。。。",
    ],
    // 相爱的时间 记住格式不能写错了, 非常重要
    // 格式一定要和下面这个时间格式一样
    // 分别是 年-月-日T时时:分分:秒秒
    //      温馨警告:
    //          1.时分秒都必须是俩个数字  比如 00:00:00
    //          2.T不能丢了
    date: "2019-05-03T16:00:00",
    // 双方的名字
    names: ["小锅锅", "臭猪猪"],
};
